name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Instala dependencias
      run: |
        make install
    - name: Lint con pylint
      run: |
        make lint
    - name: Pruebas con pytest
      run: |
        make test
    - name: Formatea codigo
      run: |
        make format
